//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioNotas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasEstudiantes
    {
        public int IdAlumno { get; set; }
        public string Nombre { get; set; }
        public string Labouno { get; set; }
        public string Labodos { get; set; }
        public string Labotres { get; set; }
        public string parcialuno { get; set; }
        public string parcialdos { get; set; }
        public string parcialtres { get; set; }
    }
}
